APP/blueprints/home.py
import random
from flask import Blueprint, render_template, request
from flask import render_template, flash, redirect, url_for, Blueprint
from flask_login import login_user, logout_user, login_required, current_user

from APP.extentions import db
from APP.models import *
from APP.forms import SearchInfo
from APP.utils import redirect_back

home = Blueprint('home', __name__)


def init_home(app):
    app.register_blueprint(blueprint=home)


@home.route('/search/', methods=['GET', 'POST'])
def search():
    form = SearchInfo()
    if form.validate_on_submit():
        pages = request.args.get("page", 1, type=int)
        per_page = request.args.get("per_page", 3, type=int)

        seachtype = form.SearchType.data
        searchInfo = form.SearchInfo.data
        print(seachtype)
        print(searchInfo)
        if seachtype == 'BID':
            books = Book.query.filter(Book.BID.like('%{}%'.format(searchInfo))).all()
        if seachtype == 'BookName':
            books = Book.query.filter(Book.bName.like('%{}%'.format(searchInfo))).all()
        if seachtype == 'Category':
            books = Book.query.filter(Book.Category.like('%{}%'.format(searchInfo))).all()
        if seachtype == 'Press':
            books = Book.query.filter(Book.press.like('%{}%'.format(searchInfo))).all()
        if seachtype == 'Author':
            books = Book.query.filter(Book.author.like('%{}%'.format(searchInfo))).all()
        if books != None:
            print(books[0].bName)
            return render_template('library/search.html', form=form, booksList=books)
    return render_template('library/search.html', form=form)


@login_required
@home.route('/borrow/')
def borrow():
    BID = request.args.get('BID', type=int)
    book = Book.query.get(BID)
    if book.currNum > 0:
        book.currNum = book.currNum - 1
        flash('Borrowed.', 'info')
        db.session.commit()
    else:
        flash('No book now!', 'danger')
    return redirect_back()


@home.route('/allb/')
def allb():
    book = Book()
    book.publicationDate = '1234-2-1'
    db.session.add(book)
    db.session.commit()
    searchInfo = '123'
    books = Book.query.filter(Book.BID.like('%{}%'.format(searchInfo))).all()
    print(books)
    return render_template('library/all.html', books=books)

templates/adminBase.html
{% extends 'bootstrap/base.html' %}

{% block navbar %}
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('admin.index') }}">Library</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">

                    <li class="active">
                        <a href="{{ url_for('admin.book_manage') }}">图书管理 <span class="sr-only">(current)</span></a>
                    </li>
                    <li>
                        <a href="{{ url_for('admin.add_book') }}">新增图书</a>
                    </li>
                    <li>
                        <a href="{{ url_for('admin.return_book') }}">图书归还</a>
                    </li>
                    <li>
                        <a href="{{ url_for('admin.reader_manage') }}">读者管理</a>
                    </li>
                </ul>
                <form class="navbar-form navbar-left">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Search">
                    </div>
                    <button type="submit" class="btn btn-default">Submit</button>
                </form>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="#">Link</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">{{ current_user.rName }} <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Action</a></li>
                            <li><a href="#">Another action</a></li>
                            <li><a href="#">Something else here</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="{{ url_for("auth.logout") }}">Log out</a></li>
                        </ul>
                    </li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
{% endblock %}

templates/macros.html
{% macro render_pagination(pagination, endpoint) %}

    <nav aria-label="Page navigation">
        <ul class="pagination">

            <div class=pagination>
                {% if pagination.has_prev %}
                    <li>
                        <a href="{{ url_for(endpoint, page=pagination.prev_num) }}" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                {% else %}
                    <li class="disabled">
                        <a href="#" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                {% endif %}
                {%- for page in pagination.iter_pages() %}
                    {% if page %}
                        {% if page != pagination.page %}

                            <li>
                                <a href="{{ url_for(endpoint, page=page) }}">{{ page }}</a>
                            </li>

                        {% else %}
                            <li class="active">
                                <a href="#"><strong>{{ page }}</strong></a>
                            </li>
                        {% endif %}
                    {% else %}
                        <li>
                            <a href="#">
                                <span class=ellipsis>…</span>
                            </a>
                        </li>
                    {% endif %}
                {%- endfor %}
                {% if pagination.has_next %}
                    <li>
                        <a href="{{ url_for(endpoint, page=pagination.next_num) }}" aria-label="Previous">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                {% else %}
                    <li class="disabled">
                        <a href="#" aria-label="Previous">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                {% endif %}
            </div>


        </ul>
    </nav>
{% endmacro %}

templates/mybase.html
{% extends 'bootstrap/base.html' %}

{% block navbar %}
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('auth.index') }}">Library</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">

                    <li class="active">
                        <a href="{{ url_for('home.search') }}">图书查询 <span class="sr-only">(current)</span></a>
                    </li>
                    <li>
                        <a href="#">Link</a>
                    </li>
                </ul>
                <form class="navbar-form navbar-left">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Search">
                    </div>
                    <button type="submit" class="btn btn-default">Submit</button>
                </form>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="#">Link</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">{{ current_user.rName }} <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Action</a></li>
                            <li><a href="#">Another action</a></li>
                            <li><a href="#">Something else here</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="{{ url_for("auth.logout") }}">Log out</a></li>
                        </ul>
                    </li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
{% endblock %}

templates/personList.html
{% extends 'library/home.html' %}
{% from "macros.html" import render_pagination %}

{% block content %}
    <main>
        {% for message in get_flashed_messages(with_categories=True) %}
            <div class="alert alert-{{ message[0] }}" role="alert">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ message[1] }}
            </div>
        {% endfor %}

    </main>

    <!-- 触发模态弹出窗的元素 -->
    <button type="button" data-toggle="modal" data-target="#mymodal" class="btn btn-primary">点击我会弹出模态弹出窗</button>
    <!-- 模态弹出窗 -->
    <div class="modal fade" id="mymodal">
        <div class="modal-dialog">
            <div class="modal-content">
                !boom
                <!-- 模态弹出窗内容 -->
            </div>
        </div>
    </div>

    <div class="container">

        <ul>
            {% for person in personList.items %}
                <li>{{ person.ID }}</li>
            {% endfor %}
        </ul>

        {{ render_pagination(personList, "auth.pag") }}
    </div>
{% endblock %}