APP/blueprints/home.py
import random
from flask import Blueprint, render_template, request
from flask import render_template, flash, redirect, url_for, Blueprint
from flask_login import login_user, logout_user, login_required, current_user

from APP.extentions import db
from APP.models import *
from APP.forms import SearchInfo
from APP.utils import redirect_back

home = Blueprint('home', __name__)


def init_home(app):
    app.register_blueprint(blueprint=home)


@home.route('/search/', methods=['GET', 'POST'])
def search():
    form = SearchInfo()
    if form.validate_on_submit():
        pages = request.args.get("page", 1, type=int)
        per_page = request.args.get("per_page", 3, type=int)

        seachtype = form.SearchType.data
        searchInfo = form.SearchInfo.data
        print(seachtype)
        print(searchInfo)
        if seachtype == 'BID':
            books = Book.query.filter(Book.BID.like('%{}%'.format(searchInfo))).all()
        if seachtype == 'BookName':
            books = Book.query.filter(Book.bName.like('%{}%'.format(searchInfo))).all()
        if seachtype == 'Category':
            books = Book.query.filter(Book.Category.like('%{}%'.format(searchInfo))).all()
        if seachtype == 'Press':
            books = Book.query.filter(Book.press.like('%{}%'.format(searchInfo))).all()
        if seachtype == 'Author':
            books = Book.query.filter(Book.author.like('%{}%'.format(searchInfo))).all()
        if books != None:
            print(books[0].bName)
            return render_template('library/search.html', form=form, booksList=books)
    return render_template('library/search.html', form=form)


@login_required
@home.route('/borrow/')
def borrow():
    BID = request.args.get('BID', type=int)
    book = Book.query.get(BID)
    if book.currNum > 0:
        book.currNum = book.currNum - 1
        flash('Borrowed.', 'info')
        db.session.commit()
    else:
        flash('No book now!', 'danger')
    return redirect_back()


@home.route('/allb/')
def allb():
    book = Book()
    book.publicationDate = '1234-2-1'
    db.session.add(book)
    db.session.commit()
    searchInfo = '123'
    books = Book.query.filter(Book.BID.like('%{}%'.format(searchInfo))).all()
    print(books)
    return render_template('library/all.html', books=books)

templates/library/all.html
{% extends 'library/home.html' %}

{% block content %}
    {% for book in books %}
        {{ book.BID }}
    {% endfor %}

{% endblock %}

templates/library/home.html
{% extends 'mybase.html' %}


{% block content %}
    <main>
        {% for message in get_flashed_messages(with_categories=True) %}
            <div class="alert alert-{{ message[0] }}" role="alert">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ message[1] }}
            </div>
        {% endfor %}
    </main>

    <div class="container">
        <div class="jumbotron">
            <h1>
                {{ current_user.rName }}!
            </h1>
            <p>
                ...
            </p>
            <p>
                <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
            </p>
        </div>
    </div>
{% endblock %}

templates/library/search.html
{% extends 'mybase.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
    <main>
        {% for message in get_flashed_messages(with_categories=True) %}
            <div class="alert alert-{{ message[0] }}" role="alert">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ message[1] }}
            </div>
        {% endfor %}
    </main>

    <div class="col-md-4">
        {{ wtf.quick_form(form) }}
    </div>


    <table class="table table-hover">
        <thead>
        <th>BID</th>
        <th>封面</th>
        <th>标题</th>
        <th>作者</th>
        <th>分类</th>
        <th>在馆位置</th>
        <th>在馆数量</th>
        <th>操作</th>
        </thead>
        <tbody>
        {% for book in booksList %}
            <tr>
                <td>{{ book.BID }}</td>
                <td>
                    bookImg
                </td>
                <td><a href="#">{{ book.bName }}</a></td>
                <td>{{ book.author }}</td>
                <td>{{ book.Category }}</td>
                <td>{{ book.press }}</td>
                <td>{{ book.currNum }}</td>
                <td>

                    <a class="btn btn-info glyphicon glyphicon-thumbs-up btn-sm" href="{{ url_for('home.borrow', BID=book.BID) }}">借阅此书</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>


{% endblock %}

templates/library/searchResults.html
{% extends 'library/search.html' %}
{% block content %}
    {{ super() }}

{% endblock %}
</div>